    on:
      push:    
        branches:    
          - master
    
    
    
    
    
    
    
    
    
    
    jobs:
      build:
        runs-on: ubuntu-latest 
            
        steps:
          - name: 'testing github action'
            run: pwd
          
            
          - name: 'testing printing'
            run: echo Ali 
            
          - name: 'printing folder content before'
            run: ls  
          
          - uses: actions/checkout@v3 
          
          - name: 'printing folder content after'
            run: ls
            
            
          - name: 'login to dockerhub'
            run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}  