    on:
      push:    
        branches:    
          - master
    
    
    
    
    
    
    
    
    
    
    jobs:
      build:
        runs-on: ubuntu-latest 
            
        steps:
          - name: 'testing github action'
            run: pwd
          
            
          - name: 'testing printing'
            run: echo Ali  
          
          - uses: actions/checkout@v3 
          
          - name: 'printing folder content'
            run: ls
            
            
          - name: 'login to dockerhub'
            run: docker login --usename hamedeng23 --password dckr_pat_uPi6Eihg9rHx2qm90-mUzaXZrJU  